### ISSUE TITLE
"td3d_is_s3dis-3d-5class_pretrain.py" does not exist

### ISSUE THREAD

**Issue by xiongcs** [SamsungLabs/td3d#21]
I can't find the file "td3d _ is _ s3dis-3d-5 class _ pretrain.py".

**Comment by xiongcs** [comment]
![图片](https://github.com/SamsungLabs/td3d/assets/151824485/be338643-717d-49c0-9d4f-62e460e9ead7)

**Comment by filaPro** [comment]
Please use ...13class... instead of ...5class...
