### ISSUE TITLE
Issue about instance segmentation visualization on S3DIS dataset

### ISSUE THREAD

**Issue by Roomnum** [SamsungLabs/td3d#27]
Hello, author！ Thank you for your incredible work！ I was wondering about instance segmentation visualization on S3DIS dataset: 
after finishing test and generating some .obj files below,  where is instance label?  I open these these .obj files in MeshLab, it seems like semantic segmentation, not instance segmentation.    
![微信图片_20241127162500](https://github.com/user-attachments/assets/182e596e-d78f-4be7-88c0-29373aa6d66b)
Hope you can reply this issue!!! Thank you!!!

**Comment by filaPro** [comment]
can you please provide some screenshots of this prediction in meshlab?

**Comment by Roomnum** [comment]
> can you please provide some screenshots of this prediction in meshlab?您能否在 MeshLab 中提供此预测的一些屏幕截图？
![ins](https://github.com/user-attachments/assets/62f5d077-77f3-437f-bb59-dfb3442fd6e5)
by the way, why is my class "stem" results all zero?
![test](https://github.com/user-attachments/assets/0e75b08b-7ae3-4bd7-994f-adc324cf1c19)
 Thank you for your reply!!!

**Comment by Roomnum** [comment]
> > can you please provide some screenshots of this prediction in meshlab?您能否在 MeshLab 中提供此预测的一些屏幕截图？
> > ![ins](https://private-user-images.githubusercontent.com/180152153/390340193-62f5d077-77f3-437f-bb59-dfb3442fd6e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MDQ4NDQsIm5iZiI6MTczMjcwNDU0NCwicGF0aCI6Ii8xODAxNTIxNTMvMzkwMzQwMTkzLTYyZjVkMDc3LTc3ZjMtNDM3Zi1iYjU5LWRmYjM0NDJmZDZlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QxMDQ5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NWM1NGQ4N2U4YjdkMzhjODRjZTUwMjc0ZTkzMjdkMGEzMmM3YzJmOTJmYTY3YmY0MGFhNDhkMTJjZmY2N2MwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4sj2Z4-P8H6sxjGRWUIQJjzDimCllWn887TouamKN3Q)
> > by the way, why is my class "stem" results all zero?
> > ![test](https://private-user-images.githubusercontent.com/180152153/390340611-0e75b08b-7ae3-4bd7-994f-adc324cf1c19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MDQ4NDQsIm5iZiI6MTczMjcwNDU0NCwicGF0aCI6Ii8xODAxNTIxNTMvMzkwMzQwNjExLTBlNzViMDhiLTdhZTMtNGJkNy05OTRmLWFkYzMyNGNmMWMxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QxMDQ5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDYzYjZhNjljMmQwZTZjYzliMjE4YmNlOWZlNDYxYTNlM2VkMzJlMjI5ZjVjMTg0ZDdlMTdkYzA3MGVhMTNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oDzARX6clC31-Vo7F5i-8v33AYh09V4aPR1NpzZJl4g)
> > Thank you for your reply!!!

I solved this issue just now and retrain the model, if it doesn't have any problem next, I will close this comment.

**Comment by Roomnum** [comment]
Q: Hello, author! Still me. I was confused about the low metrics of the result using my own dataset. All parameters are default, and I train 330 epochs. Could you explain it or give me some advice about parameters?   Thank you!!!   Sincerely hope you can reply this comment.
![wenti](https://github.com/user-attachments/assets/d9e8d2f5-9d6f-4f5f-910a-da46f4bea93c)
