### ISSUE TITLE
How long does it take for training.

### ISSUE THREAD

**Issue by bxiang233** [SamsungLabs/td3d#3]
Hi, thanks for your great job! In your paper, you mentioned that you train for 330 epochs on a single NVidia 3090 GPU, using Adam optimizer. May I ask how long does it take? How many days/hours? Look forward to your reply. Thank you in advance!

**Comment by col14m** [comment]
Hi, @bxiang233 
It depends on the dataset. For example, on ScanNet it takes about 24 hours, on S3DIS - about 8 hours.
