### ISSUE TITLE
About the result of wall.

### ISSUE THREAD

**Issue by cainiaoshidai** [SamsungLabs/td3d#7]
Hi,
    It's a nice work. I found that the current methods rarely deal with the boundary.How does your method compare to Mask3D about results on the wall boundary?
I'm looking forward to hearing back from you.
Best.

**Comment by filaPro** [comment]
Hi @cainiaoshidai ,

I think we mainly focused on standard metrics like mAP for different IoU. So it's hard to say any particular information about the metrics for wall boundaries.

**Comment by cainiaoshidai** [comment]
@filaPro Thanks for your reply. I might have to do some more research.
